title: Smart Crytocurrency Rules Act
author: Yaël Ossowski
  name: yaeloss
  email: yael@consumerchoicecenter.org

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  Write an awesome description for your new site here. You can edit this line
  in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

# Build settings

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme-specific settings

minima:
  # Minima date format.
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  #
  # date_format: "%b %-d, %Y"

  # Generate social links in footer.
  #
  # social_links:
  #   - { platform: facebook,       user_url: "https://www.facebook.com/consumerchoicec" }
  #   - { platform: github,         user_url: "https://github.com/yaeloss/Smart-Cryptocurrency-Rules-Act" }
  #   - { platform: instagram,      user_url: "https://www.instagram.com/consumerchoicec" }
  #   - { platform: keybase,        user_url: "https://keybase.io/yael" }
  #   - { platform: twitter,        user_url: "https://twitter.com/consumerchoicec" }
  #   - { platform: youtube,        user_url: "https://www.youtube.com/consumerchoicec" }

# If you want to link only specific pages in your header, uncomment this and add the path to the pages in
# order as they should show up.
#
# header_pages:
#   - about.md

# Set to `true` to show excerpts on the homepage.
#
# show_excerpts: false
